[technote]
id = "TSTN-048"
series_id = "TSTN"
canonical_url = "https://tstn-048.lsst.io"
github_url = "https://github.com/lsst-tstn/tstn-048"
github_default_branch = "main"
date_created = 2024-09-09T21:08:54Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Tiago"
name.family = "Ribeiro"
internal_id = "ribeirot"

[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"
